spring:
  application:
    name : store
  datasource:
    url : jdbc:mysql://localhost:3000/store?createDatabaseIfNotExist=true
    username : root
    password : admin@123
  jpa:
    show-sql : true
user:
  paymentGateway : paypal
server:
  host : https://mavic.com
  port : 2000